version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}

secrets:
  vmware_password:
    file: ~/docker/secrets/vmware_password.txt

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=3d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://prom.local.lan:9090'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    depends_on:
      - prometheus
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://alerts.local.lan:9093'

  grafana:
    image: grafana/grafana:latest
    user: "472"
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel, flant-statusmap-panel, marcusolsson-treemap-panel"
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  vmware-exporter:
    image: pryorda/vmware_exporter:latest
    depends_on:
      - prometheus
    ports:
      - "9272:9272"
    environment:
      VSPHERE_HOST: "vcsa-1.local.lan"
      VSPHERE_USER: "administrator@vsphere.local"
      VSPHERE_PASSWORD: /run/secrets/vmware_password
      VSPHERE_IGNORE_SSL: "True"
    restart: unless-stopped
    secrets:
      - vmware_password

  blackbox:
    image: prom/blackbox-exporter:latest
    ports:
      - 9115:9115
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
      - ./loki/rules.yml:/tmp/loki/rules/fake/rules.yml
      - loki_data:/loki
    restart: unless-stopped

  snmp:
    image: quay.io/prometheus/snmp-exporter:latest
    volumes:
      - ./snmp:/etc/snmp_exporter
    ports:
      - 9116:9116
      - 116:116/udp
    command: --config.file=/etc/snmp_exporter/snmp.yml
    restart: unless-stopped

  rsyslog:
    image: rsyslog/syslog_appliance_alpine:latest
    depends_on:
      - loki
    ports:
      - 514:514
      - 514:514/udp
    volumes:
      - ./rsyslog/rsyslog.conf:/config/rsyslog.conf
    environment:
      RSYSLOG_CONF: "/config/rsyslog.conf"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    depends_on:
      - rsyslog
    volumes:
      - ./promtail/promtail-syslog.yml:/etc/promtail/promtail-syslog.yml
    command: -config.file=/etc/promtail/promtail-syslog.yml
    restart: unless-stopped

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    depends_on:
      - grafana
      - prometheus
    volumes:
      - ./unpoller/up.conf:/etc/unpoller/up.conf
    restart: unless-stopped